CREATE TABLE com_districts(
   id       INTEGER  NOT NULL PRIMARY KEY 
  ,state_id INTEGER  NOT NULL
  ,name     VARCHAR(36) NOT NULL
);
INSERT INTO com_districts(id,state_id,name) VALUES (1,1,'North Andaman');
INSERT INTO com_districts(id,state_id,name) VALUES (2,1,'South Andaman');
INSERT INTO com_districts(id,state_id,name) VALUES (3,1,'Nicobar');
INSERT INTO com_districts(id,state_id,name) VALUES (4,2,'Adilabad');
INSERT INTO com_districts(id,state_id,name) VALUES (5,2,'Anantapur');
INSERT INTO com_districts(id,state_id,name) VALUES (6,2,'Chittoor');
INSERT INTO com_districts(id,state_id,name) VALUES (7,2,'East Godavari');
INSERT INTO com_districts(id,state_id,name) VALUES (8,2,'Guntur');
INSERT INTO com_districts(id,state_id,name) VALUES (9,2,'Hyderabad');
INSERT INTO com_districts(id,state_id,name) VALUES (10,2,'Karimnagar');
INSERT INTO com_districts(id,state_id,name) VALUES (11,2,'Khammam');
INSERT INTO com_districts(id,state_id,name) VALUES (12,2,'Krishna');
INSERT INTO com_districts(id,state_id,name) VALUES (13,2,'Kurnool');
INSERT INTO com_districts(id,state_id,name) VALUES (14,2,'Mahbubnagar');
INSERT INTO com_districts(id,state_id,name) VALUES (15,2,'Medak');
INSERT INTO com_districts(id,state_id,name) VALUES (16,2,'Nalgonda');
INSERT INTO com_districts(id,state_id,name) VALUES (17,2,'Nizamabad');
INSERT INTO com_districts(id,state_id,name) VALUES (18,2,'Prakasam');
INSERT INTO com_districts(id,state_id,name) VALUES (19,2,'Ranga Reddy');
INSERT INTO com_districts(id,state_id,name) VALUES (20,2,'Srikakulam');
INSERT INTO com_districts(id,state_id,name) VALUES (21,2,'Sri Potti Sri Ramulu Nellore');
INSERT INTO com_districts(id,state_id,name) VALUES (22,2,'Vishakhapatnam');
INSERT INTO com_districts(id,state_id,name) VALUES (23,2,'Vizianagaram');
INSERT INTO com_districts(id,state_id,name) VALUES (24,2,'Warangal');
INSERT INTO com_districts(id,state_id,name) VALUES (25,2,'West Godavari');
INSERT INTO com_districts(id,state_id,name) VALUES (26,2,'Cudappah');
INSERT INTO com_districts(id,state_id,name) VALUES (27,3,'Anjaw');
INSERT INTO com_districts(id,state_id,name) VALUES (28,3,'Changlang');
INSERT INTO com_districts(id,state_id,name) VALUES (29,3,'East Siang');
INSERT INTO com_districts(id,state_id,name) VALUES (30,3,'East Kameng');
INSERT INTO com_districts(id,state_id,name) VALUES (31,3,'Kurung Kumey');
INSERT INTO com_districts(id,state_id,name) VALUES (32,3,'Lohit');
INSERT INTO com_districts(id,state_id,name) VALUES (33,3,'Lower Dibang Valley');
INSERT INTO com_districts(id,state_id,name) VALUES (34,3,'Lower Subansiri');
INSERT INTO com_districts(id,state_id,name) VALUES (35,3,'Papum Pare');
INSERT INTO com_districts(id,state_id,name) VALUES (36,3,'Tawang');
INSERT INTO com_districts(id,state_id,name) VALUES (37,3,'Tirap');
INSERT INTO com_districts(id,state_id,name) VALUES (38,3,'Dibang Valley');
INSERT INTO com_districts(id,state_id,name) VALUES (39,3,'Upper Siang');
INSERT INTO com_districts(id,state_id,name) VALUES (40,3,'Upper Subansiri');
INSERT INTO com_districts(id,state_id,name) VALUES (41,3,'West Kameng');
INSERT INTO com_districts(id,state_id,name) VALUES (42,3,'West Siang');
INSERT INTO com_districts(id,state_id,name) VALUES (43,4,'Baksa');
INSERT INTO com_districts(id,state_id,name) VALUES (44,4,'Barpeta');
INSERT INTO com_districts(id,state_id,name) VALUES (45,4,'Bongaigaon');
INSERT INTO com_districts(id,state_id,name) VALUES (46,4,'Cachar');
INSERT INTO com_districts(id,state_id,name) VALUES (47,4,'Chirang');
INSERT INTO com_districts(id,state_id,name) VALUES (48,4,'Darrang');
INSERT INTO com_districts(id,state_id,name) VALUES (49,4,'Dhemaji');
INSERT INTO com_districts(id,state_id,name) VALUES (50,4,'Dima Hasao');
INSERT INTO com_districts(id,state_id,name) VALUES (51,4,'Dhubri');
INSERT INTO com_districts(id,state_id,name) VALUES (52,4,'Dibrugarh');
INSERT INTO com_districts(id,state_id,name) VALUES (53,4,'Goalpara');
INSERT INTO com_districts(id,state_id,name) VALUES (54,4,'Golaghat');
INSERT INTO com_districts(id,state_id,name) VALUES (55,4,'Hailakandi');
INSERT INTO com_districts(id,state_id,name) VALUES (56,4,'Jorhat');
INSERT INTO com_districts(id,state_id,name) VALUES (57,4,'Kamrup');
INSERT INTO com_districts(id,state_id,name) VALUES (58,4,'Kamrup Metropolitan');
INSERT INTO com_districts(id,state_id,name) VALUES (59,4,'Karbi Anglong');
INSERT INTO com_districts(id,state_id,name) VALUES (60,4,'Karimganj');
INSERT INTO com_districts(id,state_id,name) VALUES (61,4,'Kokrajhar');
INSERT INTO com_districts(id,state_id,name) VALUES (62,4,'Lakhimpur');
INSERT INTO com_districts(id,state_id,name) VALUES (63,4,'Morigaon');
INSERT INTO com_districts(id,state_id,name) VALUES (64,4,'Nagaon');
INSERT INTO com_districts(id,state_id,name) VALUES (65,4,'Nalbari');
INSERT INTO com_districts(id,state_id,name) VALUES (66,4,'Sivasagar');
INSERT INTO com_districts(id,state_id,name) VALUES (67,4,'Sonitpur');
INSERT INTO com_districts(id,state_id,name) VALUES (68,4,'Tinsukia');
INSERT INTO com_districts(id,state_id,name) VALUES (69,4,'Udalguri');
INSERT INTO com_districts(id,state_id,name) VALUES (70,5,'Araria');
INSERT INTO com_districts(id,state_id,name) VALUES (71,5,'Arwal');
INSERT INTO com_districts(id,state_id,name) VALUES (72,5,'Aurangabad');
INSERT INTO com_districts(id,state_id,name) VALUES (73,5,'Banka');
INSERT INTO com_districts(id,state_id,name) VALUES (74,5,'Begusarai');
INSERT INTO com_districts(id,state_id,name) VALUES (75,5,'Bhagalpur');
INSERT INTO com_districts(id,state_id,name) VALUES (76,5,'Bhojpur');
INSERT INTO com_districts(id,state_id,name) VALUES (77,5,'Buxar');
INSERT INTO com_districts(id,state_id,name) VALUES (78,5,'Darbhanga');
INSERT INTO com_districts(id,state_id,name) VALUES (79,5,'East Champaran');
INSERT INTO com_districts(id,state_id,name) VALUES (80,5,'Gaya');
INSERT INTO com_districts(id,state_id,name) VALUES (81,5,'Gopalganj');
INSERT INTO com_districts(id,state_id,name) VALUES (82,5,'Jamui');
INSERT INTO com_districts(id,state_id,name) VALUES (83,5,'Jehanabad');
INSERT INTO com_districts(id,state_id,name) VALUES (84,5,'Kaimur');
INSERT INTO com_districts(id,state_id,name) VALUES (85,5,'Katihar');
INSERT INTO com_districts(id,state_id,name) VALUES (86,5,'Khagaria');
INSERT INTO com_districts(id,state_id,name) VALUES (87,5,'Kishanganj');
INSERT INTO com_districts(id,state_id,name) VALUES (88,5,'Lakhisarai');
INSERT INTO com_districts(id,state_id,name) VALUES (89,5,'Madhepura');
INSERT INTO com_districts(id,state_id,name) VALUES (90,5,'Madhubani');
INSERT INTO com_districts(id,state_id,name) VALUES (91,5,'Munger');
INSERT INTO com_districts(id,state_id,name) VALUES (92,5,'Muzaffarpur');
INSERT INTO com_districts(id,state_id,name) VALUES (93,5,'Nalanda');
INSERT INTO com_districts(id,state_id,name) VALUES (94,5,'Nawada');
INSERT INTO com_districts(id,state_id,name) VALUES (95,5,'Patna');
INSERT INTO com_districts(id,state_id,name) VALUES (96,5,'Purnia');
INSERT INTO com_districts(id,state_id,name) VALUES (97,5,'Rohtas');
INSERT INTO com_districts(id,state_id,name) VALUES (98,5,'Saharsa');
INSERT INTO com_districts(id,state_id,name) VALUES (99,5,'Samastipur');
INSERT INTO com_districts(id,state_id,name) VALUES (100,5,'Saran');
INSERT INTO com_districts(id,state_id,name) VALUES (101,5,'Sheikhpura');
INSERT INTO com_districts(id,state_id,name) VALUES (102,5,'Sheohar');
INSERT INTO com_districts(id,state_id,name) VALUES (103,5,'Sitamarhi');
INSERT INTO com_districts(id,state_id,name) VALUES (104,5,'Siwan');
INSERT INTO com_districts(id,state_id,name) VALUES (105,5,'Supaul');
INSERT INTO com_districts(id,state_id,name) VALUES (106,6,'Chandigarh');
INSERT INTO com_districts(id,state_id,name) VALUES (107,7,'Bastar');
INSERT INTO com_districts(id,state_id,name) VALUES (108,7,'Bijapur');
INSERT INTO com_districts(id,state_id,name) VALUES (109,7,'Bilaspur');
INSERT INTO com_districts(id,state_id,name) VALUES (110,7,'Dantewada');
INSERT INTO com_districts(id,state_id,name) VALUES (111,7,'Dhamtari');
INSERT INTO com_districts(id,state_id,name) VALUES (112,7,'Durg');
INSERT INTO com_districts(id,state_id,name) VALUES (113,7,'Jashpur');
INSERT INTO com_districts(id,state_id,name) VALUES (114,7,'Janjgir-Champa');
INSERT INTO com_districts(id,state_id,name) VALUES (115,7,'Korba');
INSERT INTO com_districts(id,state_id,name) VALUES (116,7,'Koriya');
INSERT INTO com_districts(id,state_id,name) VALUES (117,7,'Kanker');
INSERT INTO com_districts(id,state_id,name) VALUES (118,7,'Kabirdham (formerly Kawardha)');
INSERT INTO com_districts(id,state_id,name) VALUES (119,7,'Mahasamund');
INSERT INTO com_districts(id,state_id,name) VALUES (120,7,'Narayanpur');
INSERT INTO com_districts(id,state_id,name) VALUES (121,7,'Raigarh');
INSERT INTO com_districts(id,state_id,name) VALUES (122,7,'Rajnandgaon');
INSERT INTO com_districts(id,state_id,name) VALUES (123,7,'Raipur');
INSERT INTO com_districts(id,state_id,name) VALUES (124,7,'Surguja');
INSERT INTO com_districts(id,state_id,name) VALUES (125,8,'Dadra and Nagar Haveli');
INSERT INTO com_districts(id,state_id,name) VALUES (126,9,'Daman');
INSERT INTO com_districts(id,state_id,name) VALUES (127,9,'Diu');
INSERT INTO com_districts(id,state_id,name) VALUES (128,10,'Central Delhi');
INSERT INTO com_districts(id,state_id,name) VALUES (129,10,'East Delhi');
INSERT INTO com_districts(id,state_id,name) VALUES (130,10,'New Delhi');
INSERT INTO com_districts(id,state_id,name) VALUES (131,10,'North Delhi');
INSERT INTO com_districts(id,state_id,name) VALUES (132,10,'North East Delhi');
INSERT INTO com_districts(id,state_id,name) VALUES (133,10,'North West Delhi');
INSERT INTO com_districts(id,state_id,name) VALUES (134,10,'South Delhi');
INSERT INTO com_districts(id,state_id,name) VALUES (135,10,'South West Delhi');
INSERT INTO com_districts(id,state_id,name) VALUES (136,10,'West Delhi');
INSERT INTO com_districts(id,state_id,name) VALUES (137,11,'North Goa');
INSERT INTO com_districts(id,state_id,name) VALUES (138,11,'South Goa');
INSERT INTO com_districts(id,state_id,name) VALUES (139,12,'Ahmedabad');
INSERT INTO com_districts(id,state_id,name) VALUES (140,12,'Amreli district');
INSERT INTO com_districts(id,state_id,name) VALUES (141,12,'Anand');
INSERT INTO com_districts(id,state_id,name) VALUES (142,12,'Banaskantha');
INSERT INTO com_districts(id,state_id,name) VALUES (143,12,'Bharuch');
INSERT INTO com_districts(id,state_id,name) VALUES (144,12,'Bhavnagar');
INSERT INTO com_districts(id,state_id,name) VALUES (145,12,'Dahod');
INSERT INTO com_districts(id,state_id,name) VALUES (146,12,'The Dangs');
INSERT INTO com_districts(id,state_id,name) VALUES (147,12,'Gandhinagar');
INSERT INTO com_districts(id,state_id,name) VALUES (148,12,'Jamnagar');
INSERT INTO com_districts(id,state_id,name) VALUES (149,12,'Junagadh');
INSERT INTO com_districts(id,state_id,name) VALUES (150,12,'Kutch');
INSERT INTO com_districts(id,state_id,name) VALUES (151,12,'Kheda');
INSERT INTO com_districts(id,state_id,name) VALUES (152,12,'Mehsana');
INSERT INTO com_districts(id,state_id,name) VALUES (153,12,'Narmada');
INSERT INTO com_districts(id,state_id,name) VALUES (154,12,'Navsari');
INSERT INTO com_districts(id,state_id,name) VALUES (155,12,'Patan');
INSERT INTO com_districts(id,state_id,name) VALUES (156,12,'Panchmahal');
INSERT INTO com_districts(id,state_id,name) VALUES (157,12,'Porbandar');
INSERT INTO com_districts(id,state_id,name) VALUES (158,12,'Rajkot');
INSERT INTO com_districts(id,state_id,name) VALUES (159,12,'Sabarkantha');
INSERT INTO com_districts(id,state_id,name) VALUES (160,12,'Surendranagar');
INSERT INTO com_districts(id,state_id,name) VALUES (161,12,'Surat');
INSERT INTO com_districts(id,state_id,name) VALUES (162,12,'Tapi');
INSERT INTO com_districts(id,state_id,name) VALUES (163,12,'Vadodara');
INSERT INTO com_districts(id,state_id,name) VALUES (164,12,'Valsad');
INSERT INTO com_districts(id,state_id,name) VALUES (165,13,'Ambala');
INSERT INTO com_districts(id,state_id,name) VALUES (166,13,'Bhiwani');
INSERT INTO com_districts(id,state_id,name) VALUES (167,13,'Faridabad');
INSERT INTO com_districts(id,state_id,name) VALUES (168,13,'Fatehabad');
INSERT INTO com_districts(id,state_id,name) VALUES (169,13,'Gurgaon');
INSERT INTO com_districts(id,state_id,name) VALUES (170,13,'Hissar');
INSERT INTO com_districts(id,state_id,name) VALUES (171,13,'Jhajjar');
INSERT INTO com_districts(id,state_id,name) VALUES (172,13,'Jind');
INSERT INTO com_districts(id,state_id,name) VALUES (173,13,'Karnal');
INSERT INTO com_districts(id,state_id,name) VALUES (174,13,'Kaithal');
INSERT INTO com_districts(id,state_id,name) VALUES (175,13,'Kurukshetra');
INSERT INTO com_districts(id,state_id,name) VALUES (176,13,'Mahendragarh');
INSERT INTO com_districts(id,state_id,name) VALUES (177,13,'Mewat');
INSERT INTO com_districts(id,state_id,name) VALUES (178,13,'Palwal');
INSERT INTO com_districts(id,state_id,name) VALUES (179,13,'Panchkula');
INSERT INTO com_districts(id,state_id,name) VALUES (180,13,'Panipat');
INSERT INTO com_districts(id,state_id,name) VALUES (181,13,'Rewari');
INSERT INTO com_districts(id,state_id,name) VALUES (182,13,'Rohtak');
INSERT INTO com_districts(id,state_id,name) VALUES (183,13,'Sirsa');
INSERT INTO com_districts(id,state_id,name) VALUES (184,13,'Sonipat');
INSERT INTO com_districts(id,state_id,name) VALUES (185,13,'Yamuna Nagar');
INSERT INTO com_districts(id,state_id,name) VALUES (186,14,'Bilaspur');
INSERT INTO com_districts(id,state_id,name) VALUES (187,14,'Chamba');
INSERT INTO com_districts(id,state_id,name) VALUES (188,14,'Hamirpur');
INSERT INTO com_districts(id,state_id,name) VALUES (189,14,'Kangra');
INSERT INTO com_districts(id,state_id,name) VALUES (190,14,'Kinnaur');
INSERT INTO com_districts(id,state_id,name) VALUES (191,14,'Kullu');
INSERT INTO com_districts(id,state_id,name) VALUES (192,14,'Lahaul and Spiti');
INSERT INTO com_districts(id,state_id,name) VALUES (193,14,'Mandi');
INSERT INTO com_districts(id,state_id,name) VALUES (194,14,'Shimla');
INSERT INTO com_districts(id,state_id,name) VALUES (195,14,'Sirmaur');
INSERT INTO com_districts(id,state_id,name) VALUES (196,14,'Solan');
INSERT INTO com_districts(id,state_id,name) VALUES (197,14,'Una');
INSERT INTO com_districts(id,state_id,name) VALUES (198,15,'Anantnag');
INSERT INTO com_districts(id,state_id,name) VALUES (199,15,'Badgam');
INSERT INTO com_districts(id,state_id,name) VALUES (200,15,'Bandipora');
INSERT INTO com_districts(id,state_id,name) VALUES (201,15,'Baramulla');
INSERT INTO com_districts(id,state_id,name) VALUES (202,15,'Doda');
INSERT INTO com_districts(id,state_id,name) VALUES (203,15,'Ganderbal');
INSERT INTO com_districts(id,state_id,name) VALUES (204,15,'Jammu');
INSERT INTO com_districts(id,state_id,name) VALUES (205,15,'Kargil');
INSERT INTO com_districts(id,state_id,name) VALUES (206,15,'Kathua');
INSERT INTO com_districts(id,state_id,name) VALUES (207,15,'Kishtwar');
INSERT INTO com_districts(id,state_id,name) VALUES (208,15,'Kupwara');
INSERT INTO com_districts(id,state_id,name) VALUES (209,15,'Kulgam');
INSERT INTO com_districts(id,state_id,name) VALUES (210,15,'Leh');
INSERT INTO com_districts(id,state_id,name) VALUES (211,15,'Poonch');
INSERT INTO com_districts(id,state_id,name) VALUES (212,15,'Pulwama');
INSERT INTO com_districts(id,state_id,name) VALUES (213,15,'Rajouri');
INSERT INTO com_districts(id,state_id,name) VALUES (214,15,'Ramban');
INSERT INTO com_districts(id,state_id,name) VALUES (215,15,'Reasi');
INSERT INTO com_districts(id,state_id,name) VALUES (216,15,'Samba');
INSERT INTO com_districts(id,state_id,name) VALUES (217,15,'Shopian');
INSERT INTO com_districts(id,state_id,name) VALUES (218,15,'Srinagar');
INSERT INTO com_districts(id,state_id,name) VALUES (219,15,'Udhampur');
INSERT INTO com_districts(id,state_id,name) VALUES (220,16,'Bokaro');
INSERT INTO com_districts(id,state_id,name) VALUES (221,16,'Chatra');
INSERT INTO com_districts(id,state_id,name) VALUES (222,16,'Deoghar');
INSERT INTO com_districts(id,state_id,name) VALUES (223,16,'Dhanbad');
INSERT INTO com_districts(id,state_id,name) VALUES (224,16,'Dumka');
INSERT INTO com_districts(id,state_id,name) VALUES (225,16,'East Singhbhum');
INSERT INTO com_districts(id,state_id,name) VALUES (226,16,'Garhwa');
INSERT INTO com_districts(id,state_id,name) VALUES (227,16,'Giridih');
INSERT INTO com_districts(id,state_id,name) VALUES (228,16,'Godda');
INSERT INTO com_districts(id,state_id,name) VALUES (229,16,'Gumla');
INSERT INTO com_districts(id,state_id,name) VALUES (230,16,'Hazaribag');
INSERT INTO com_districts(id,state_id,name) VALUES (231,16,'Jamtara');
INSERT INTO com_districts(id,state_id,name) VALUES (232,16,'Khunti');
INSERT INTO com_districts(id,state_id,name) VALUES (233,16,'Koderma');
INSERT INTO com_districts(id,state_id,name) VALUES (234,16,'Latehar');
INSERT INTO com_districts(id,state_id,name) VALUES (235,16,'Lohardaga');
INSERT INTO com_districts(id,state_id,name) VALUES (236,16,'Pakur');
INSERT INTO com_districts(id,state_id,name) VALUES (237,16,'Palamu');
INSERT INTO com_districts(id,state_id,name) VALUES (238,16,'Ramgarh');
INSERT INTO com_districts(id,state_id,name) VALUES (239,16,'Ranchi');
INSERT INTO com_districts(id,state_id,name) VALUES (240,16,'Sahibganj');
INSERT INTO com_districts(id,state_id,name) VALUES (241,16,'Seraikela Kharsawan');
INSERT INTO com_districts(id,state_id,name) VALUES (242,16,'Simdega');
INSERT INTO com_districts(id,state_id,name) VALUES (243,16,'West Singhbhum');
INSERT INTO com_districts(id,state_id,name) VALUES (244,17,'Bagalkot');
INSERT INTO com_districts(id,state_id,name) VALUES (245,17,'Bangalore Rural');
INSERT INTO com_districts(id,state_id,name) VALUES (246,17,'Bangalore Urban');
INSERT INTO com_districts(id,state_id,name) VALUES (247,17,'Belgaum');
INSERT INTO com_districts(id,state_id,name) VALUES (248,17,'Bellary');
INSERT INTO com_districts(id,state_id,name) VALUES (249,17,'Bidar');
INSERT INTO com_districts(id,state_id,name) VALUES (250,17,'Bijapur');
INSERT INTO com_districts(id,state_id,name) VALUES (251,17,'Chamarajnagar');
INSERT INTO com_districts(id,state_id,name) VALUES (252,17,'Chikkamagaluru');
INSERT INTO com_districts(id,state_id,name) VALUES (253,17,'Chikkaballapur');
INSERT INTO com_districts(id,state_id,name) VALUES (254,17,'Chitradurga');
INSERT INTO com_districts(id,state_id,name) VALUES (255,17,'Davanagere');
INSERT INTO com_districts(id,state_id,name) VALUES (256,17,'Dharwad');
INSERT INTO com_districts(id,state_id,name) VALUES (257,17,'Dakshina Kannada');
INSERT INTO com_districts(id,state_id,name) VALUES (258,17,'Gadag');
INSERT INTO com_districts(id,state_id,name) VALUES (259,17,'Gulbarga');
INSERT INTO com_districts(id,state_id,name) VALUES (260,17,'Hassan');
INSERT INTO com_districts(id,state_id,name) VALUES (261,17,'Haveri district');
INSERT INTO com_districts(id,state_id,name) VALUES (262,17,'Kodagu');
INSERT INTO com_districts(id,state_id,name) VALUES (263,17,'Kolar');
INSERT INTO com_districts(id,state_id,name) VALUES (264,17,'Koppal');
INSERT INTO com_districts(id,state_id,name) VALUES (265,17,'Mandya');
INSERT INTO com_districts(id,state_id,name) VALUES (266,17,'Mysore');
INSERT INTO com_districts(id,state_id,name) VALUES (267,17,'Raichur');
INSERT INTO com_districts(id,state_id,name) VALUES (268,17,'Shimoga');
INSERT INTO com_districts(id,state_id,name) VALUES (269,17,'Tumkur');
INSERT INTO com_districts(id,state_id,name) VALUES (270,17,'Udupi');
INSERT INTO com_districts(id,state_id,name) VALUES (271,17,'Uttara Kannada');
INSERT INTO com_districts(id,state_id,name) VALUES (272,17,'Ramanagara');
INSERT INTO com_districts(id,state_id,name) VALUES (273,17,'Yadgir');
INSERT INTO com_districts(id,state_id,name) VALUES (274,18,'Alappuzha');
INSERT INTO com_districts(id,state_id,name) VALUES (275,18,'Ernakulam');
INSERT INTO com_districts(id,state_id,name) VALUES (276,18,'Idukki');
INSERT INTO com_districts(id,state_id,name) VALUES (277,18,'Kannur');
INSERT INTO com_districts(id,state_id,name) VALUES (278,18,'Kasaragod');
INSERT INTO com_districts(id,state_id,name) VALUES (279,18,'Kollam');
INSERT INTO com_districts(id,state_id,name) VALUES (280,18,'Kottayam');
INSERT INTO com_districts(id,state_id,name) VALUES (281,18,'Kozhikode');
INSERT INTO com_districts(id,state_id,name) VALUES (282,18,'Malappuram');
INSERT INTO com_districts(id,state_id,name) VALUES (283,18,'Palakkad');
INSERT INTO com_districts(id,state_id,name) VALUES (284,18,'Pathanamthitta');
INSERT INTO com_districts(id,state_id,name) VALUES (285,18,'Thrissur');
INSERT INTO com_districts(id,state_id,name) VALUES (286,18,'Thiruvananthapuram');
INSERT INTO com_districts(id,state_id,name) VALUES (287,18,'Wayanad');
INSERT INTO com_districts(id,state_id,name) VALUES (288,19,'Lakshadweep');
INSERT INTO com_districts(id,state_id,name) VALUES (289,20,'Agar');
INSERT INTO com_districts(id,state_id,name) VALUES (290,20,'Alirajpur');
INSERT INTO com_districts(id,state_id,name) VALUES (291,20,'Anuppur');
INSERT INTO com_districts(id,state_id,name) VALUES (292,20,'Ashok Nagar');
INSERT INTO com_districts(id,state_id,name) VALUES (293,20,'Balaghat');
INSERT INTO com_districts(id,state_id,name) VALUES (294,20,'Barwani');
INSERT INTO com_districts(id,state_id,name) VALUES (295,20,'Betul');
INSERT INTO com_districts(id,state_id,name) VALUES (296,20,'Bhind');
INSERT INTO com_districts(id,state_id,name) VALUES (297,20,'Bhopal');
INSERT INTO com_districts(id,state_id,name) VALUES (298,20,'Burhanpur');
INSERT INTO com_districts(id,state_id,name) VALUES (299,20,'Chhatarpur');
INSERT INTO com_districts(id,state_id,name) VALUES (300,20,'Chhindwara');
INSERT INTO com_districts(id,state_id,name) VALUES (301,20,'Damoh');
INSERT INTO com_districts(id,state_id,name) VALUES (302,20,'Datia');
INSERT INTO com_districts(id,state_id,name) VALUES (303,20,'Dewas');
INSERT INTO com_districts(id,state_id,name) VALUES (304,20,'Dhar');
INSERT INTO com_districts(id,state_id,name) VALUES (305,20,'Dindori');
INSERT INTO com_districts(id,state_id,name) VALUES (306,20,'Guna');
INSERT INTO com_districts(id,state_id,name) VALUES (307,20,'Gwalior');
INSERT INTO com_districts(id,state_id,name) VALUES (308,20,'Harda');
INSERT INTO com_districts(id,state_id,name) VALUES (309,20,'Hoshangabad');
INSERT INTO com_districts(id,state_id,name) VALUES (310,20,'Indore');
INSERT INTO com_districts(id,state_id,name) VALUES (311,20,'Jabalpur');
INSERT INTO com_districts(id,state_id,name) VALUES (312,20,'Jhabua');
INSERT INTO com_districts(id,state_id,name) VALUES (313,20,'Katni');
INSERT INTO com_districts(id,state_id,name) VALUES (314,20,'Khandwa (East Nimar)');
INSERT INTO com_districts(id,state_id,name) VALUES (315,20,'Khargone (West Nimar)');
INSERT INTO com_districts(id,state_id,name) VALUES (316,20,'Mandla');
INSERT INTO com_districts(id,state_id,name) VALUES (317,20,'Mandsaur');
INSERT INTO com_districts(id,state_id,name) VALUES (318,20,'Morena');
INSERT INTO com_districts(id,state_id,name) VALUES (319,20,'Narsinghpur');
INSERT INTO com_districts(id,state_id,name) VALUES (320,20,'Neemuch');
INSERT INTO com_districts(id,state_id,name) VALUES (321,20,'Panna');
INSERT INTO com_districts(id,state_id,name) VALUES (322,20,'Raisen');
INSERT INTO com_districts(id,state_id,name) VALUES (323,20,'Rajgarh');
INSERT INTO com_districts(id,state_id,name) VALUES (324,20,'Ratlam');
INSERT INTO com_districts(id,state_id,name) VALUES (325,20,'Rewa');
INSERT INTO com_districts(id,state_id,name) VALUES (326,20,'Sagar');
INSERT INTO com_districts(id,state_id,name) VALUES (327,20,'Satna');
INSERT INTO com_districts(id,state_id,name) VALUES (328,20,'Sehore');
INSERT INTO com_districts(id,state_id,name) VALUES (329,20,'Seoni');
INSERT INTO com_districts(id,state_id,name) VALUES (330,20,'Shahdol');
INSERT INTO com_districts(id,state_id,name) VALUES (331,20,'Shajapur');
INSERT INTO com_districts(id,state_id,name) VALUES (332,20,'Sheopur');
INSERT INTO com_districts(id,state_id,name) VALUES (333,20,'Shivpuri');
INSERT INTO com_districts(id,state_id,name) VALUES (334,20,'Sidhi');
INSERT INTO com_districts(id,state_id,name) VALUES (335,20,'Singrauli');
INSERT INTO com_districts(id,state_id,name) VALUES (336,20,'Tikamgarh');
INSERT INTO com_districts(id,state_id,name) VALUES (337,20,'Ujjain');
INSERT INTO com_districts(id,state_id,name) VALUES (338,20,'Umaria');
INSERT INTO com_districts(id,state_id,name) VALUES (339,20,'Vidisha');
INSERT INTO com_districts(id,state_id,name) VALUES (340,21,'Ahmednagar');
INSERT INTO com_districts(id,state_id,name) VALUES (341,21,'Akola');
INSERT INTO com_districts(id,state_id,name) VALUES (342,21,'Amravati');
INSERT INTO com_districts(id,state_id,name) VALUES (343,21,'Aurangabad');
INSERT INTO com_districts(id,state_id,name) VALUES (344,21,'Beed');
INSERT INTO com_districts(id,state_id,name) VALUES (345,21,'Bhandara');
INSERT INTO com_districts(id,state_id,name) VALUES (346,21,'Buldhana');
INSERT INTO com_districts(id,state_id,name) VALUES (347,21,'Chandrapur');
INSERT INTO com_districts(id,state_id,name) VALUES (348,21,'Dhule');
INSERT INTO com_districts(id,state_id,name) VALUES (349,21,'Gadchiroli');
INSERT INTO com_districts(id,state_id,name) VALUES (350,21,'Gondia');
INSERT INTO com_districts(id,state_id,name) VALUES (351,21,'Hingoli');
INSERT INTO com_districts(id,state_id,name) VALUES (352,21,'Jalgaon');
INSERT INTO com_districts(id,state_id,name) VALUES (353,21,'Jalna');
INSERT INTO com_districts(id,state_id,name) VALUES (354,21,'Kolhapur');
INSERT INTO com_districts(id,state_id,name) VALUES (355,21,'Latur');
INSERT INTO com_districts(id,state_id,name) VALUES (356,21,'Mumbai City');
INSERT INTO com_districts(id,state_id,name) VALUES (357,21,'Mumbai suburban');
INSERT INTO com_districts(id,state_id,name) VALUES (358,21,'Nanded');
INSERT INTO com_districts(id,state_id,name) VALUES (359,21,'Nandurbar');
INSERT INTO com_districts(id,state_id,name) VALUES (360,21,'Nagpur');
INSERT INTO com_districts(id,state_id,name) VALUES (361,21,'Nashik');
INSERT INTO com_districts(id,state_id,name) VALUES (362,21,'Osmanabad');
INSERT INTO com_districts(id,state_id,name) VALUES (363,21,'Parbhani');
INSERT INTO com_districts(id,state_id,name) VALUES (364,21,'Pune');
INSERT INTO com_districts(id,state_id,name) VALUES (365,21,'Raigad');
INSERT INTO com_districts(id,state_id,name) VALUES (366,21,'Ratnagiri');
INSERT INTO com_districts(id,state_id,name) VALUES (367,21,'Sangli');
INSERT INTO com_districts(id,state_id,name) VALUES (368,21,'Satara');
INSERT INTO com_districts(id,state_id,name) VALUES (369,21,'Sindhudurg');
INSERT INTO com_districts(id,state_id,name) VALUES (370,21,'Solapur');
INSERT INTO com_districts(id,state_id,name) VALUES (371,21,'Thane');
INSERT INTO com_districts(id,state_id,name) VALUES (372,21,'Wardha');
INSERT INTO com_districts(id,state_id,name) VALUES (373,21,'Washim');
INSERT INTO com_districts(id,state_id,name) VALUES (374,21,'Yavatmal');
INSERT INTO com_districts(id,state_id,name) VALUES (375,22,'Bishnupur');
INSERT INTO com_districts(id,state_id,name) VALUES (376,22,'Churachandpur');
INSERT INTO com_districts(id,state_id,name) VALUES (377,22,'Chandel');
INSERT INTO com_districts(id,state_id,name) VALUES (378,22,'Imphal East');
INSERT INTO com_districts(id,state_id,name) VALUES (379,22,'Senapati');
INSERT INTO com_districts(id,state_id,name) VALUES (380,22,'Tamenglong');
INSERT INTO com_districts(id,state_id,name) VALUES (381,22,'Thoubal');
INSERT INTO com_districts(id,state_id,name) VALUES (382,22,'Ukhrul');
INSERT INTO com_districts(id,state_id,name) VALUES (383,22,'Imphal West');
INSERT INTO com_districts(id,state_id,name) VALUES (384,23,'East Garo Hills');
INSERT INTO com_districts(id,state_id,name) VALUES (385,23,'East Khasi Hills');
INSERT INTO com_districts(id,state_id,name) VALUES (386,23,'Jaintia Hills');
INSERT INTO com_districts(id,state_id,name) VALUES (387,23,'Ri Bhoi');
INSERT INTO com_districts(id,state_id,name) VALUES (388,23,'South Garo Hills');
INSERT INTO com_districts(id,state_id,name) VALUES (389,23,'West Garo Hills');
INSERT INTO com_districts(id,state_id,name) VALUES (390,23,'West Khasi Hills');
INSERT INTO com_districts(id,state_id,name) VALUES (391,24,'Aizawl');
INSERT INTO com_districts(id,state_id,name) VALUES (392,24,'Champhai');
INSERT INTO com_districts(id,state_id,name) VALUES (393,24,'Kolasib');
INSERT INTO com_districts(id,state_id,name) VALUES (394,24,'Lawngtlai');
INSERT INTO com_districts(id,state_id,name) VALUES (395,24,'Lunglei');
INSERT INTO com_districts(id,state_id,name) VALUES (396,24,'Mamit');
INSERT INTO com_districts(id,state_id,name) VALUES (397,24,'Saiha');
INSERT INTO com_districts(id,state_id,name) VALUES (398,24,'Serchhip');
INSERT INTO com_districts(id,state_id,name) VALUES (399,25,'Dimapur');
INSERT INTO com_districts(id,state_id,name) VALUES (400,25,'Kiphire');
INSERT INTO com_districts(id,state_id,name) VALUES (401,25,'Kohima');
INSERT INTO com_districts(id,state_id,name) VALUES (402,25,'Longleng');
INSERT INTO com_districts(id,state_id,name) VALUES (403,25,'Mokokchung');
INSERT INTO com_districts(id,state_id,name) VALUES (404,25,'Mon');
INSERT INTO com_districts(id,state_id,name) VALUES (405,25,'Peren');
INSERT INTO com_districts(id,state_id,name) VALUES (406,25,'Phek');
INSERT INTO com_districts(id,state_id,name) VALUES (407,25,'Tuensang');
INSERT INTO com_districts(id,state_id,name) VALUES (408,25,'Wokha');
INSERT INTO com_districts(id,state_id,name) VALUES (409,25,'Zunheboto');
INSERT INTO com_districts(id,state_id,name) VALUES (410,26,'Angul');
INSERT INTO com_districts(id,state_id,name) VALUES (411,26,'Boudh (Bauda)');
INSERT INTO com_districts(id,state_id,name) VALUES (412,26,'Bhadrak');
INSERT INTO com_districts(id,state_id,name) VALUES (413,26,'Balangir');
INSERT INTO com_districts(id,state_id,name) VALUES (414,26,'Bargarh (Baragarh)');
INSERT INTO com_districts(id,state_id,name) VALUES (415,26,'Balasore');
INSERT INTO com_districts(id,state_id,name) VALUES (416,26,'Cuttack');
INSERT INTO com_districts(id,state_id,name) VALUES (417,26,'Debagarh (Deogarh)');
INSERT INTO com_districts(id,state_id,name) VALUES (418,26,'Dhenkanal');
INSERT INTO com_districts(id,state_id,name) VALUES (419,26,'Ganjam');
INSERT INTO com_districts(id,state_id,name) VALUES (420,26,'Gajapati');
INSERT INTO com_districts(id,state_id,name) VALUES (421,26,'Jharsuguda');
INSERT INTO com_districts(id,state_id,name) VALUES (422,26,'Jajpur');
INSERT INTO com_districts(id,state_id,name) VALUES (423,26,'Jagatsinghpur');
INSERT INTO com_districts(id,state_id,name) VALUES (424,26,'Khordha');
INSERT INTO com_districts(id,state_id,name) VALUES (425,26,'Kendujhar (Keonjhar)');
INSERT INTO com_districts(id,state_id,name) VALUES (426,26,'Kalahandi');
INSERT INTO com_districts(id,state_id,name) VALUES (427,26,'Kandhamal');
INSERT INTO com_districts(id,state_id,name) VALUES (428,26,'Koraput');
INSERT INTO com_districts(id,state_id,name) VALUES (429,26,'Kendrapara');
INSERT INTO com_districts(id,state_id,name) VALUES (430,26,'Malkangiri');
INSERT INTO com_districts(id,state_id,name) VALUES (431,26,'Mayurbhanj');
INSERT INTO com_districts(id,state_id,name) VALUES (432,26,'Nabarangpur');
INSERT INTO com_districts(id,state_id,name) VALUES (433,26,'Nuapada');
INSERT INTO com_districts(id,state_id,name) VALUES (434,26,'Nayagarh');
INSERT INTO com_districts(id,state_id,name) VALUES (435,26,'Puri');
INSERT INTO com_districts(id,state_id,name) VALUES (436,26,'Rayagada');
INSERT INTO com_districts(id,state_id,name) VALUES (437,26,'Sambalpur');
INSERT INTO com_districts(id,state_id,name) VALUES (438,26,'Subarnapur (Sonepur)');
INSERT INTO com_districts(id,state_id,name) VALUES (439,26,'Sundergarh');
INSERT INTO com_districts(id,state_id,name) VALUES (440,27,'Karaikal');
INSERT INTO com_districts(id,state_id,name) VALUES (441,27,'Mahe');
INSERT INTO com_districts(id,state_id,name) VALUES (442,27,'Pondicherry');
INSERT INTO com_districts(id,state_id,name) VALUES (443,27,'Yanam');
INSERT INTO com_districts(id,state_id,name) VALUES (444,28,'Amritsar');
INSERT INTO com_districts(id,state_id,name) VALUES (445,28,'Barnala');
INSERT INTO com_districts(id,state_id,name) VALUES (446,28,'Bathinda');
INSERT INTO com_districts(id,state_id,name) VALUES (447,28,'Firozpur');
INSERT INTO com_districts(id,state_id,name) VALUES (448,28,'Faridkot');
INSERT INTO com_districts(id,state_id,name) VALUES (449,28,'Fatehgarh Sahib');
INSERT INTO com_districts(id,state_id,name) VALUES (450,28,'Fazilka[6]');
INSERT INTO com_districts(id,state_id,name) VALUES (451,28,'Gurdaspur');
INSERT INTO com_districts(id,state_id,name) VALUES (452,28,'Hoshiarpur');
INSERT INTO com_districts(id,state_id,name) VALUES (453,28,'Jalandhar');
INSERT INTO com_districts(id,state_id,name) VALUES (454,28,'Kapurthala');
INSERT INTO com_districts(id,state_id,name) VALUES (455,28,'Ludhiana');
INSERT INTO com_districts(id,state_id,name) VALUES (456,28,'Mansa');
INSERT INTO com_districts(id,state_id,name) VALUES (457,28,'Moga');
INSERT INTO com_districts(id,state_id,name) VALUES (458,28,'Sri Muktsar Sahib');
INSERT INTO com_districts(id,state_id,name) VALUES (459,28,'Pathankot');
INSERT INTO com_districts(id,state_id,name) VALUES (460,28,'Patiala');
INSERT INTO com_districts(id,state_id,name) VALUES (461,28,'Rupnagar');
INSERT INTO com_districts(id,state_id,name) VALUES (462,28,'Ajitgarh (Mohali)');
INSERT INTO com_districts(id,state_id,name) VALUES (463,28,'Sangrur');
INSERT INTO com_districts(id,state_id,name) VALUES (464,28,'Shahid Bhagat Singh Nagar');
INSERT INTO com_districts(id,state_id,name) VALUES (465,28,'Tarn Taran');
INSERT INTO com_districts(id,state_id,name) VALUES (466,29,'Ajmer');
INSERT INTO com_districts(id,state_id,name) VALUES (467,29,'Alwar');
INSERT INTO com_districts(id,state_id,name) VALUES (468,29,'Bikaner');
INSERT INTO com_districts(id,state_id,name) VALUES (469,29,'Barmer');
INSERT INTO com_districts(id,state_id,name) VALUES (470,29,'Banswara');
INSERT INTO com_districts(id,state_id,name) VALUES (471,29,'Bharatpur');
INSERT INTO com_districts(id,state_id,name) VALUES (472,29,'Baran');
INSERT INTO com_districts(id,state_id,name) VALUES (473,29,'Bundi');
INSERT INTO com_districts(id,state_id,name) VALUES (474,29,'Bhilwara');
INSERT INTO com_districts(id,state_id,name) VALUES (475,29,'Churu');
INSERT INTO com_districts(id,state_id,name) VALUES (476,29,'Chittorgarh');
INSERT INTO com_districts(id,state_id,name) VALUES (477,29,'Dausa');
INSERT INTO com_districts(id,state_id,name) VALUES (478,29,'Dholpur');
INSERT INTO com_districts(id,state_id,name) VALUES (479,29,'Dungapur');
INSERT INTO com_districts(id,state_id,name) VALUES (480,29,'Ganganagar');
INSERT INTO com_districts(id,state_id,name) VALUES (481,29,'Hanumangarh');
INSERT INTO com_districts(id,state_id,name) VALUES (482,29,'Jhunjhunu');
INSERT INTO com_districts(id,state_id,name) VALUES (483,29,'Jalore');
INSERT INTO com_districts(id,state_id,name) VALUES (484,29,'Jodhpur');
INSERT INTO com_districts(id,state_id,name) VALUES (485,29,'Jaipur');
INSERT INTO com_districts(id,state_id,name) VALUES (486,29,'Jaisalmer');
INSERT INTO com_districts(id,state_id,name) VALUES (487,29,'Jhalawar');
INSERT INTO com_districts(id,state_id,name) VALUES (488,29,'Karauli');
INSERT INTO com_districts(id,state_id,name) VALUES (489,29,'Kota');
INSERT INTO com_districts(id,state_id,name) VALUES (490,29,'Nagaur');
INSERT INTO com_districts(id,state_id,name) VALUES (491,29,'Pali');
INSERT INTO com_districts(id,state_id,name) VALUES (492,29,'Pratapgarh');
INSERT INTO com_districts(id,state_id,name) VALUES (493,29,'Rajsamand');
INSERT INTO com_districts(id,state_id,name) VALUES (494,29,'Sikar');
INSERT INTO com_districts(id,state_id,name) VALUES (495,29,'Sawai Madhopur');
INSERT INTO com_districts(id,state_id,name) VALUES (496,29,'Sirohi');
INSERT INTO com_districts(id,state_id,name) VALUES (497,29,'Tonk');
INSERT INTO com_districts(id,state_id,name) VALUES (498,29,'Udaipur');
INSERT INTO com_districts(id,state_id,name) VALUES (499,30,'East Sikkim');
INSERT INTO com_districts(id,state_id,name) VALUES (500,30,'North Sikkim');
INSERT INTO com_districts(id,state_id,name) VALUES (501,30,'South Sikkim');
INSERT INTO com_districts(id,state_id,name) VALUES (502,30,'West Sikkim');
INSERT INTO com_districts(id,state_id,name) VALUES (503,31,'Ariyalur');
INSERT INTO com_districts(id,state_id,name) VALUES (504,31,'Chennai');
INSERT INTO com_districts(id,state_id,name) VALUES (505,31,'Coimbatore');
INSERT INTO com_districts(id,state_id,name) VALUES (506,31,'Cuddalore');
INSERT INTO com_districts(id,state_id,name) VALUES (507,31,'Dharmapuri');
INSERT INTO com_districts(id,state_id,name) VALUES (508,31,'Dindigul');
INSERT INTO com_districts(id,state_id,name) VALUES (509,31,'Erode');
INSERT INTO com_districts(id,state_id,name) VALUES (510,31,'Kanchipuram');
INSERT INTO com_districts(id,state_id,name) VALUES (511,31,'Kanyakumari');
INSERT INTO com_districts(id,state_id,name) VALUES (512,31,'Karur');
INSERT INTO com_districts(id,state_id,name) VALUES (513,31,'Krishnagiri');
INSERT INTO com_districts(id,state_id,name) VALUES (514,31,'Madurai');
INSERT INTO com_districts(id,state_id,name) VALUES (515,31,'Nagapattinam');
INSERT INTO com_districts(id,state_id,name) VALUES (516,31,'Nilgiris');
INSERT INTO com_districts(id,state_id,name) VALUES (517,31,'Namakkal');
INSERT INTO com_districts(id,state_id,name) VALUES (518,31,'Perambalur');
INSERT INTO com_districts(id,state_id,name) VALUES (519,31,'Pudukkottai');
INSERT INTO com_districts(id,state_id,name) VALUES (520,31,'Ramanathapuram');
INSERT INTO com_districts(id,state_id,name) VALUES (521,31,'Salem');
INSERT INTO com_districts(id,state_id,name) VALUES (522,31,'Sivaganga');
INSERT INTO com_districts(id,state_id,name) VALUES (523,31,'Tirupur');
INSERT INTO com_districts(id,state_id,name) VALUES (524,31,'Tiruchirappalli');
INSERT INTO com_districts(id,state_id,name) VALUES (525,31,'Theni');
INSERT INTO com_districts(id,state_id,name) VALUES (526,31,'Tirunelveli');
INSERT INTO com_districts(id,state_id,name) VALUES (527,31,'Thanjavur');
INSERT INTO com_districts(id,state_id,name) VALUES (528,31,'Thoothukudi');
INSERT INTO com_districts(id,state_id,name) VALUES (529,31,'Tiruvallur');
INSERT INTO com_districts(id,state_id,name) VALUES (530,31,'Tiruvarur');
INSERT INTO com_districts(id,state_id,name) VALUES (531,31,'Tiruvannamalai');
INSERT INTO com_districts(id,state_id,name) VALUES (532,31,'Vellore');
INSERT INTO com_districts(id,state_id,name) VALUES (533,31,'Viluppuram');
INSERT INTO com_districts(id,state_id,name) VALUES (534,31,'Virudhunagar');
INSERT INTO com_districts(id,state_id,name) VALUES (535,32,'Dhalai');
INSERT INTO com_districts(id,state_id,name) VALUES (536,32,'North Tripura');
INSERT INTO com_districts(id,state_id,name) VALUES (537,32,'South Tripura');
INSERT INTO com_districts(id,state_id,name) VALUES (538,32,'Khowai[7]');
INSERT INTO com_districts(id,state_id,name) VALUES (539,32,'West Tripura');
INSERT INTO com_districts(id,state_id,name) VALUES (540,33,'Agra');
INSERT INTO com_districts(id,state_id,name) VALUES (541,33,'Aligarh');
INSERT INTO com_districts(id,state_id,name) VALUES (542,33,'Allahabad');
INSERT INTO com_districts(id,state_id,name) VALUES (543,33,'Ambedkar Nagar');
INSERT INTO com_districts(id,state_id,name) VALUES (544,33,'Auraiya');
INSERT INTO com_districts(id,state_id,name) VALUES (545,33,'Azamgarh');
INSERT INTO com_districts(id,state_id,name) VALUES (546,33,'Bagpat');
INSERT INTO com_districts(id,state_id,name) VALUES (547,33,'Bahraich');
INSERT INTO com_districts(id,state_id,name) VALUES (548,33,'Ballia');
INSERT INTO com_districts(id,state_id,name) VALUES (549,33,'Balrampur');
INSERT INTO com_districts(id,state_id,name) VALUES (550,33,'Banda');
INSERT INTO com_districts(id,state_id,name) VALUES (551,33,'Barabanki');
INSERT INTO com_districts(id,state_id,name) VALUES (552,33,'Bareilly');
INSERT INTO com_districts(id,state_id,name) VALUES (553,33,'Basti');
INSERT INTO com_districts(id,state_id,name) VALUES (554,33,'Bijnor');
INSERT INTO com_districts(id,state_id,name) VALUES (555,33,'Budaun');
INSERT INTO com_districts(id,state_id,name) VALUES (556,33,'Bulandshahr');
INSERT INTO com_districts(id,state_id,name) VALUES (557,33,'Chandauli');
INSERT INTO com_districts(id,state_id,name) VALUES (558,33,'Chhatrapati Shahuji Maharaj Nagar[8]');
INSERT INTO com_districts(id,state_id,name) VALUES (559,33,'Chitrakoot');
INSERT INTO com_districts(id,state_id,name) VALUES (560,33,'Deoria');
INSERT INTO com_districts(id,state_id,name) VALUES (561,33,'Etah');
INSERT INTO com_districts(id,state_id,name) VALUES (562,33,'Etawah');
INSERT INTO com_districts(id,state_id,name) VALUES (563,33,'Faizabad');
INSERT INTO com_districts(id,state_id,name) VALUES (564,33,'Farrukhabad');
INSERT INTO com_districts(id,state_id,name) VALUES (565,33,'Fatehpur');
INSERT INTO com_districts(id,state_id,name) VALUES (566,33,'Firozabad');
INSERT INTO com_districts(id,state_id,name) VALUES (567,33,'Gautam Buddh Nagar');
INSERT INTO com_districts(id,state_id,name) VALUES (568,33,'Ghaziabad');
INSERT INTO com_districts(id,state_id,name) VALUES (569,33,'Ghazipur');
INSERT INTO com_districts(id,state_id,name) VALUES (570,33,'Gonda');
INSERT INTO com_districts(id,state_id,name) VALUES (571,33,'Gorakhpur');
INSERT INTO com_districts(id,state_id,name) VALUES (572,33,'Hamirpur');
INSERT INTO com_districts(id,state_id,name) VALUES (573,33,'Hardoi');
INSERT INTO com_districts(id,state_id,name) VALUES (574,33,'Hathras');
INSERT INTO com_districts(id,state_id,name) VALUES (575,33,'Jalaun');
INSERT INTO com_districts(id,state_id,name) VALUES (576,33,'Jaunpur district');
INSERT INTO com_districts(id,state_id,name) VALUES (577,33,'Jhansi');
INSERT INTO com_districts(id,state_id,name) VALUES (578,33,'Jyotiba Phule Nagar');
INSERT INTO com_districts(id,state_id,name) VALUES (579,33,'Kannauj');
INSERT INTO com_districts(id,state_id,name) VALUES (580,33,'Kanpur');
INSERT INTO com_districts(id,state_id,name) VALUES (581,33,'Kanshi Ram Nagar');
INSERT INTO com_districts(id,state_id,name) VALUES (582,33,'Kaushambi');
INSERT INTO com_districts(id,state_id,name) VALUES (583,33,'Kushinagar');
INSERT INTO com_districts(id,state_id,name) VALUES (584,33,'Lakhimpur Kheri');
INSERT INTO com_districts(id,state_id,name) VALUES (585,33,'Lalitpur');
INSERT INTO com_districts(id,state_id,name) VALUES (586,33,'Lucknow');
INSERT INTO com_districts(id,state_id,name) VALUES (587,33,'Maharajganj');
INSERT INTO com_districts(id,state_id,name) VALUES (588,33,'Mahoba');
INSERT INTO com_districts(id,state_id,name) VALUES (589,33,'Mainpuri');
INSERT INTO com_districts(id,state_id,name) VALUES (590,33,'Mathura');
INSERT INTO com_districts(id,state_id,name) VALUES (591,33,'Mau');
INSERT INTO com_districts(id,state_id,name) VALUES (592,33,'Meerut');
INSERT INTO com_districts(id,state_id,name) VALUES (593,33,'Mirzapur');
INSERT INTO com_districts(id,state_id,name) VALUES (594,33,'Moradabad');
INSERT INTO com_districts(id,state_id,name) VALUES (595,33,'Muzaffarnagar');
INSERT INTO com_districts(id,state_id,name) VALUES (596,33,'Panchsheel Nagar district (Hapur)');
INSERT INTO com_districts(id,state_id,name) VALUES (597,33,'Pilibhit');
INSERT INTO com_districts(id,state_id,name) VALUES (598,33,'Pratapgarh');
INSERT INTO com_districts(id,state_id,name) VALUES (599,33,'Raebareli');
INSERT INTO com_districts(id,state_id,name) VALUES (600,33,'Ramabai Nagar (Kanpur Dehat)');
INSERT INTO com_districts(id,state_id,name) VALUES (601,33,'Rampur');
INSERT INTO com_districts(id,state_id,name) VALUES (602,33,'Saharanpur');
INSERT INTO com_districts(id,state_id,name) VALUES (603,33,'Sant Kabir Nagar');
INSERT INTO com_districts(id,state_id,name) VALUES (604,33,'Sant Ravidas Nagar');
INSERT INTO com_districts(id,state_id,name) VALUES (605,33,'Shahjahanpur');
INSERT INTO com_districts(id,state_id,name) VALUES (606,33,'Shamli[9]');
INSERT INTO com_districts(id,state_id,name) VALUES (607,33,'Shravasti');
INSERT INTO com_districts(id,state_id,name) VALUES (608,33,'Siddharthnagar');
INSERT INTO com_districts(id,state_id,name) VALUES (609,33,'Sitapur');
INSERT INTO com_districts(id,state_id,name) VALUES (610,33,'Sonbhadra');
INSERT INTO com_districts(id,state_id,name) VALUES (611,33,'Sultanpur');
INSERT INTO com_districts(id,state_id,name) VALUES (612,33,'Unnao');
INSERT INTO com_districts(id,state_id,name) VALUES (613,33,'Varanasi');
INSERT INTO com_districts(id,state_id,name) VALUES (614,34,'Almora');
INSERT INTO com_districts(id,state_id,name) VALUES (615,34,'Bageshwar');
INSERT INTO com_districts(id,state_id,name) VALUES (616,34,'Chamoli');
INSERT INTO com_districts(id,state_id,name) VALUES (617,34,'Champawat');
INSERT INTO com_districts(id,state_id,name) VALUES (618,34,'Dehradun');
INSERT INTO com_districts(id,state_id,name) VALUES (619,34,'Haridwar');
INSERT INTO com_districts(id,state_id,name) VALUES (620,34,'Nainital');
INSERT INTO com_districts(id,state_id,name) VALUES (621,34,'Pauri Garhwal');
INSERT INTO com_districts(id,state_id,name) VALUES (622,34,'Pithoragarh');
INSERT INTO com_districts(id,state_id,name) VALUES (623,34,'Rudraprayag');
INSERT INTO com_districts(id,state_id,name) VALUES (624,34,'Tehri Garhwal');
INSERT INTO com_districts(id,state_id,name) VALUES (625,34,'Udham Singh Nagar');
INSERT INTO com_districts(id,state_id,name) VALUES (626,34,'Uttarkashi');
INSERT INTO com_districts(id,state_id,name) VALUES (627,35,'Bankura');
INSERT INTO com_districts(id,state_id,name) VALUES (628,35,'Bardhaman');
INSERT INTO com_districts(id,state_id,name) VALUES (629,35,'Birbhum');
INSERT INTO com_districts(id,state_id,name) VALUES (630,35,'Cooch Behar');
INSERT INTO com_districts(id,state_id,name) VALUES (631,35,'Dakshin Dinajpur');
INSERT INTO com_districts(id,state_id,name) VALUES (632,35,'Darjeeling');
INSERT INTO com_districts(id,state_id,name) VALUES (633,35,'Hooghly');
INSERT INTO com_districts(id,state_id,name) VALUES (634,35,'Howrah');
INSERT INTO com_districts(id,state_id,name) VALUES (635,35,'Jalpaiguri');
INSERT INTO com_districts(id,state_id,name) VALUES (636,35,'Kolkata');
INSERT INTO com_districts(id,state_id,name) VALUES (637,35,'Maldah');
INSERT INTO com_districts(id,state_id,name) VALUES (638,35,'Murshidabad');
INSERT INTO com_districts(id,state_id,name) VALUES (639,35,'Nadia');
INSERT INTO com_districts(id,state_id,name) VALUES (640,35,'North 24 Parganas');
INSERT INTO com_districts(id,state_id,name) VALUES (641,35,'Paschim Medinipur');
INSERT INTO com_districts(id,state_id,name) VALUES (642,35,'Purba Medinipur');
INSERT INTO com_districts(id,state_id,name) VALUES (643,35,'Purulia');
INSERT INTO com_districts(id,state_id,name) VALUES (644,35,'South 24 Parganas');
INSERT INTO com_districts(id,state_id,name) VALUES (645,35,'Uttar Dinajpur');
